services:
  api:
    build:
      context: .
      dockerfile: gemini_datamap_api.Dockerfile
    container_name: gemini-datamap-api
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_INFERENCE_MODEL=${GEMINI_INFERENCE_MODEL:-gemini-3-flash-preview}
      - GEMINI_EMBEDDING_MODEL=${GEMINI_EMBEDDING_MODEL:-models/gemini-embedding-001}
      - DATAMAP_CONFIG_PATH=/app/config/datamap_config.json
    volumes:
      - ./config:/app/config
    networks:
      - gemini-datamap-rag
    restart: "on-failure:${RESTART_RETRIES:-300}"

  prism-mock:
    image: stoplight/prism:4
    container_name: gemini-datamap-prism-mock
    command: ["mock", "/app/SWAGGER_SAMPLE.JSON", "--host", "0.0.0.0", "--port", "4010"]
    ports:
      - "4010:4010"
    volumes:
      - ./datamap/SWAGGER_SAMPLE.JSON:/app/SWAGGER_SAMPLE.JSON:ro
    networks:
      - gemini-datamap-rag
    restart: "on-failure:${RESTART_RETRIES:-300}"


networks:
  gemini-datamap-rag:
    name: gemini-datamap-rag
    driver: bridge

