services:
  api:
    build:
      context: .
      dockerfile: gemini_datamap_api.Dockerfile
    container_name: gemini-datamap-api
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GEMINI_INFERENCE_MODEL=${GEMINI_INFERENCE_MODEL:-gemini-pro}
      - DATAMAP_CONFIG_PATH=/app/config/datamap_config.json
    volumes:
      - ./config:/app/config
    networks:
      - gemini-datamap-rag
    restart: unless-stopped


networks:
  gemini-datamap-rag:
    name: gemini-datamap-rag
    driver: bridge

